[package]
name = "revset-explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
chrono = "0.4.42"
eframe = "0.33.3"
egui_graphs = "0.29.0"
etcetera = "0.11.0"
jj-lib = "0.36.0"
petgraph = "0.8.3"
thiserror = "2.0.17"
toml = "0.9.10"
